# Set to the common workgroup name of Windows computers
[global]
   workgroup = WORKGROUP
   netbios name = balena-samba
   server string = Balena Samba Tailscale
   security = user
   map to guest = bad user
   server role = standalone server
   obey pam restrictions = yes
   socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072
   log file = /dev/stdout
   
   ; Restrict access exclusively to local interfaces and your Tailscale subnet
   hosts allow = 100.64.0.0/10 127.0.0.1
   hosts deny = 0.0.0.0/0
   
   ; Bind Samba to localhost and Tailscale adapters
   interfaces = tailscale0 lo
   bind interfaces only = yes

[Shared]
   path = /media/usbdisk
   writable = yes
   browsable = yes
   guest ok = yes
   read only = no
   force user = root
