[global]
   workgroup = WORKGROUP
   netbios name = balena-samba
   server string = Balena Samba Tailscale
   security = user
   map to guest = bad user
   server role = standalone server
   obey pam restrictions = yes
   socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072
   log file = /dev/stdout

   # Match local LAN (192.168.1.x), Tailscale (100.64.0.0/10), and local loopback
   hosts allow = 192.168.1.0/24 100.64.0.0/10 127.0.0.1 ::1
   hosts deny = ALL

[Shared]
   path = /mnt/storage
   writable = yes
   browsable = yes
   guest ok = yes
   read only = no
   force user = root
