version: '2.1'

volumes:
  storage-data:
  tailscale:

services:
  samba:
    build: samba
    container_name: samba
    restart: always
    network_mode: host
    privileged: true
    devices:
      - /dev/sda1:/dev/sda1
    labels:
        io.balena.features.dbus: '1'
    volumes:
      - storage-data:/dev/sda1
    environment:
        - UDEV=1
  tailscale:
    build: tailscale
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /var/run/
    volumes:
      - tailscale:/var/lib/tailscale