version: '2.1'

volumes:
  storage-data:
  ts-state:

services:
  samba:
    build: ./samba
    container_name: samba
    restart: always
    network_mode: host
    privileged: true
    labels:
        io.balena.features.dbus: '1'
    volumes:
      - 'storage-data:/media/usbdisk'
    environment:
        - UDEV=1
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      - io.balena.features.kernel-modules=1
    volumes:
      - 'ts-state:/var/lib/tailscale'
      - '/dev/net/tun:/dev/net/tun'
    tmpfs:
      - /tmp
      - /var/run/
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--accept-dns=true
    restart: always